### ISSUE TITLE
bd-stampy 1.0

### ISSUE THREAD

**Issue by allanhortle** [bigdatr/bd-stampy#24]
Stampy is super dooper useful but I think it's growing a bit beyond its scope and getting pretty bloated. It started as a UI library for Bigdatr but when we used it in the TRC it was clear that some components can be shared across projects and others really shouldn't be. Along with this mishmash of components there is little to no documentation which makes it hard to use for anyone who wasn't part of the initial writing. I'd like to see it progress from being a useful internal tool into something truly usable by the react community.

So that said I think the most obvious course would be to extract it away from our apps so that it is much more of a low level component library. Either by moving the Bigdatr stuff out, or by starting something new and keeping Stampy as a higher level UI library for Bigdatr.

To do this I've categorised the components, utils and mixins below into what looks good and what looks crusty. 
Please comment below with your thoughts.  All going well I'd like to start deprecating things & release a new minor version so that people have an upgrade path. Then remove that fluff and start documenting. From there I think we can start making issues to fix up the half-complete but useful stuff.
# Things to keep for v1
## Basic HTML Element Components
- Button.jsx
- Checkbox.jsx
- Fieldset.jsx
- Form.jsx
- Img.jsx
- Label.jsx
- Iframe.jsx
- Table.jsx
- Td.jsx
- Tr.jsx
- Textarea.jsx

Inputs need to be refactored down and better documented.
- Input.jsx
- InputElement.jsx
- InputForm.jsx
- InputRow.jsx

Selects are a mess. (Mostly due to me.) I've been using react-select in the TRC and found it to solve like 99% of the problems and hacks. I'd put in a vote for just having the select in Stampy to be much closer to the default HTML. If you need fancy stuff like multi/tag support and searching you can implement that in your own project. There are too many things to get exactly right for everyone.
- Select.jsx
- SelectStandard.jsx
- SelectStandardForm.jsx
## Complex Components
- DataTable.jsx
- DatePicker.jsx
- Media.jsx
- ModalPortal.jsx
- Pagination.jsx
- ProgressBar.jsx
- Tab.jsx
- TabContent.jsx
- Tabs.js
- TabView.jsx
## Unfinished

Complex components that are either just tests or have only been developed to a level that works in one of the apps.
- Animation.jsx
- Carousel.jsx
- Code.jsx
- Config.jsx
- Dropdown.jsx
- RadioButton.jsx
- ShowHide.jsx

Uploading things is super useful just a bit confusing right now. Needs a consistent props/api across the board and some documentation
- ImageUpload.jsx
- FileUpload.jsx
## Mixins / Utils
- ARIAMixin.jsx (not so sure about this, might just need a refactor)
- ClassMixin.jsx
- ElementQueryMixin.jsx
- FormEventMixin.jsx
- Key.js
- Maths.js
- Paginate.js
- ClassBuilder.js
# Things to discuss removing
## BigDatr/TRC Specific

Most of these are either made for a feature of Bigdatr or are just wrapper components that just attach a className for the CSS to hook into.
- Badge.jsx
- ButtonBar.jsx
- Choice.jsx
- Col.jsx
- ColumnDataTable.jsx
- Datetime.jsx
- Grid.jsx
- Icon.jsx
- LightBox.jsx
- List.jsx
- Loader.jsx
- Modal.jsx
- Navigation.jsx
- Typeahead.jsx
- Toast.jsx
- ToggleBox.jsx
- ToggleGroup.jsx
- Toolbar.jsx
- Video.jsx
- ViewManager.jsx
- SuperagentFileUpload.jsx
## Useless / Not sure what they are about anymore
- FilterBar.jsx
- Frame.jsx
- MagicMove.jsx
- Option.jsx
- Page.jsx
- PureRenderComponent.jsx
- Transition.jsx
# Old mixins / utils
- FormMixin.jsx
- LayoutManagerMixin.jsx
- NavMixin.jsx
- RenderMixin.jsx
- RouteMixin.jsx
- StoreMixin.jsx
- UrlStateMixin.jsx
- PortalComponentMixin.jsx
- Color.jsx
- Compare.jsx
- CSS.js // I think jsxstyle does this better.
- Dates.js
- EventEmitter.js
- Fullscreen.js
- IconStore.js
- History.js
# Things I'm completely unsure about

Someone chime in on these because I'm not sure if they are useful or not. 
- BrowserHistory.js
- UrlStore.js
- Url.js

**Comment by allanhortle** [comment]
@atridgedcosta @tchcxp

**Comment by atridgedcosta** [comment]
All looks good to me. I think everything you've listed for removal is no longer used so it should be simple to remove them and see if anything breaks :smile: 

With regards to BrowserHistory, UrlStore & Url; they should also go. I just need to refactor a little before that can happen. At the very least, we can log a deprecation warning so that it reminds us to replace it with something else like react-router or whatever.

Does Maths.js need to be in there? I'm not sure if anything in stampy actually relies on it but i could be wrong.

Another discussion we should have is how to manage css. Should we make SASS files part of the project or manage it all in JS instead (https://github.com/FormidableLabs/radium/tree/master/docs/comparison).

Docs is a must to get to 1.0 as should be tests!! Should we also upgrade everything to ES6 and use babel?

**Comment by dxinteractive** [comment]
Closing this one off, as stampy is well under way: https://github.com/bigdatr/stampy
